### ISSUE TITLE
Error downloading.

### ISSUE THREAD

**Issue by idkur** [sub3/NextPVR#1]
Error downloading. The request was aborted: Can not establish secure SSL\TLS connection.
Thats my first installation. Is there any other installer? Or a way to solve that/ I am running win7 64bit.

![Capture](https://user-images.githubusercontent.com/12982402/93286156-34926b00-f7df-11ea-98c9-d9f55d68728a.PNG)

**Comment by sub3** [comment]
Post the question on the NextPVR forums and we'll take a look. General
support like this is not done via github.

Cheers
Graeme
