### ISSUE TITLE
Could you change unicode character to ASCII code character?

### ISSUE THREAD

**Issue by zno5** [sub3/NextPVR#11]
Windows users who don't use latin language, such as English, encounter this error popup, so the installation fails.
Character ø is the reason to fail the installation.

<img width="682" alt="Screen Shot 2022-07-17 at 2 59 14 PM" src="https://user-images.githubusercontent.com/2455180/179386024-d0ebe8d5-9545-45a9-b218-b3e708335286.png">

<img width="172" alt="Screen Shot 2022-07-17 at 3 14 38 PM" src="https://user-images.githubusercontent.com/2455180/179386455-c70e236b-0956-4bd8-88be-80258ce2fb9a.png">

**Comment by sub3** [comment]
We don't do support via github. Post any issues on the forums.
