### ISSUE TITLE
`nextpvr-recording.sh` argument quoting

### ISSUE THREAD

**Issue by FreeMasen** [sub3/NextPVR#12]
The script used to update directory arguments doesn't work for the default directory structure due to the argument not being quoted.

```console
sudo  /opt/nextpvr/shell/nextpvr-recording.sh ./recordings/Manual\ Recordings/
/opt/nextpvr/shell/nextpvr-recording.sh: 1: [: ./recordings/Manual: unexpected operator
chgrp: cannot access './recordings/Manual': No such file or directory
chgrp: cannot access 'Recordings': No such file or directory
chmod: cannot access './recordings/Manual': No such file or directory
chmod: cannot access 'Recordings': No such file or directory
chmod: cannot access './recordings/Manual': No such file or directory
chmod: cannot access 'Recordings': No such file or directory
setfacl: ./recordings/Manual: No such file or directory
setfacl: Recordings: No such file or directory
```

Looking at the file, it seems like some extra quoting is needed

```sh
if [ ! -d  "$1" ]; then
	#create the folder
	mkdir -p "$1"
fi

#allow access to video group
chgrp video  "$1"

#give video group write permission
chmod +775 "$1"

# new file create with video group
chmod g+s  "$1"

# give write access to video group
setfacl -d -m g::rwX "$1"

```

This will avoid any issues with the space in the path. Escaping or quoting the argument doesn't seem to have any effect so a code change is required.

**Comment by emveepee** [comment]
Thanks you are correct and I will update it, but should know that issues should be reported on the NextPVR forum, not GitHub.

You normally shouldn't have to run this script with the default Manual\ Recordings directory because NextPVR will create it when it needs it with the proper attributes.

**Comment by emveepee** [comment]
@FreeMasen  sub updated the deb installer on nextpvr.com with your changes, thanks again.  @sub3 you can close this issue as completed.
