### ISSUE TITLE
ERROR: AddOnLog: NextPVR PVR Client: XXXXX Duration set to 0 XXXXX

### ISSUE THREAD

**Issue by wmarler** [sub3/NextPVR#2]
Kodi will crash when I attempt to skip forward in a recording.

The relevant error reported in the kodi crash log is one "AddOnLog: NextPVR PVR Client: XXXXX Duration set to 0 XXXXX". 

I've reproduced this crash on Linux (Arch) and nVidia shield. It's easier for me to pull logs from Linux, so that's what's attached here (kodi debug logging enabled, with PVR component-specific logging enabled)

[kodi_crashlog-20201011_221612.log](https://github.com/sub3/NextPVR/files/5362883/kodi_crashlog-20201011_221612.log)

**Comment by wmarler** [comment]
Here's another log file of me attempting to skip forward in the same video, however this time prior to launching kodi I wiped the EDL clear with `echo "" > NFL\ Football_20201011_11001400.edl` .

[kodi_crashlog-20201011_222700.log](https://github.com/sub3/NextPVR/files/5362913/kodi_crashlog-20201011_222700.log)

**Comment by wmarler** [comment]
Er ... sorry, I meant to file this against kodi-pvr/pvr.nextpvr. My bad.

**Comment by emveepee** [comment]
@wmarler Unless you are trying to report an issue with the code with a possible fix please post the support request on the NextPVR forum using the NextPVR support policy https://github.com/sub3/NextPVR/wiki/get-help  Logs are often easiest to send via the Kodi log uploader or using paste.kodi.tv
