### ISSUE TITLE
option for rearrange channels

### ISSUE THREAD

**Issue by CustomerJFK** [sub3/NextPVR#3]
Could you please have an option to rearrange channels. (further forward or further back ...)
Thanks!

**Comment by emveepee** [comment]
Channel numbers can be changed on the backend and then assuming you have Kodi use the backend numbers, they will be rearranged.

This is not an issue with the addon please make feature and support requests on the NextPVR forum.  @sub3 please close this.

**Comment by CustomerJFK** [comment]
Thanks
