### ISSUE TITLE
Additional IP Adresses to use with a Fritzbox 6490

### ISSUE THREAD

**Issue by cajonKA** [sub3/NextPVR#6]
The Fritzbox 6490 limits the use of its 4 receivers to one per IP Address.
All 4 receivers are automatically recognized by NextPVR.
Is there a setup possibility to assing each of the four receiver to a different IP Address of my NextPVR server so that I can record multiple streams at once ?

**Comment by emveepee** [comment]
Support like this is only on the NextPVR forum. This has nothing to do with pvr.nextpvr and only generates spam to Kodi developers.
