### ISSUE TITLE
Feature: Win-10 notifications on recording / guide problems

### ISSUE THREAD

**Issue by rmeden** [sub3/NextPVR#7]
NextPVR has been running so well for so long, I don't think about it. :)

I recently had an issue where guide downloads had errors and I didn't notice until the guide was empty.  It would be nice to get Win-10 notifications when there are guide and recording problems.

There is already a forum wishlist post about this, but there hasn't been activity in the wishlist forum, so not sure if is active... figured I'd post here. :)

**Comment by emveepee** [comment]
Bad decision since support like this is only on the NextPVR forum.   This has nothing to do with pvr.nextpvr and only generates spam to Kodi developers.  Sub has mentioned that he reads wishlist items but doesn't always to respond to them.

**Comment by sub3** [comment]
Best to leave any support / feature requests on the forums. This github repository is only really used as a location to hold the wiki.
