### ISSUE TITLE
Remote login failed for new NextPVR install

### ISSUE THREAD

**Issue by AxelTheGerman** [sub3/NextPVR#8]
Hi,
I installed NextPVR on a machine outside of my local network and cannot figure out how to log in.

First I got the error `Remote access is not enabled`.

Then I manually edited `config.xml` to `<AllowRemoteAPI>true</AllowRemoteAPI>`.

Now I still get `Remote login attempt with default credentials`.

I really appreciate that you want to make NextPVR more secure by default, but is there any way I can access it and can harden it myself?

Thanks!

**Comment by sub3** [comment]
Sorry, we don't do support via this github repository. It's only used for holding the wiki. Any support questions need to be posted on the forums.
