### ISSUE TITLE
EPG is randomly forgetting TV stations

### ISSUE THREAD

**Issue by Marty56** [sub3/NextPVR#9]
I have realized that some TV stations do not get an updated EPG.
Therefore, I have restarted NExtPVR Server and realized that now there are different TV stations that have no EPG.

Additionally I have the question whether NextPVR is still actively maintained?

[logs-20211204-0852.zip](https://github.com/sub3/NextPVR/files/7653634/logs-20211204-0852.zip)

**Comment by sub3** [comment]
Yes, NextPVR is actively maintained. 

Please post the question and logs on the NextPVR forums and we'll take a look.
